preprocessing:
  instance_type: "ml.t3.2xlarge"
  script_config:
    sample_start_date: "2018-02-01"
    sample_end_date: "2018-03-01"
    n_model_samples_per_country: 2000
    n_production_samples: 1000
    n_validation_samples: 250,
    n_test_samples: 250,
    data_file_paths:
      accounts_app: s3a://yolt-dp-dta-datascience-yoltapp-yts-sme-categories-model/input/account.csv
      accounts_yts: s3a://yolt-dp-dta-datascience-yoltapp-yts-sme-categories-model/input/account.csv
      test_users_app: s3a://yolt-dp-dta-datascience-yoltapp-yts-sme-categories-model/input/test_users.csv
      transactions_app: s3a://yolt-dp-dta-datascience-yoltapp-yts-sme-categories-model/input/transactions.csv
      transactions_yts: s3a://yolt-dp-dta-datascience-yoltapp-yts-sme-categories-model/input/transactions.csv
      users_app: s3a://yolt-dp-dta-datascience-yoltapp-yts-sme-categories-model/input/user.csv
      users_yts: s3a://yolt-dp-dta-datascience-yoltapp-yts-sme-categories-model/input/user_yts.csv

training:
  script_config:
    batch_size: 128
